### ISSUE TITLE
Reindex error

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#244]
I did a reindex on TEST with the latest PROD neo4j copy using the `test-release` branch, which uses the refactored entity-api and refactored indexer. At the time the reindex was executed, the `test-release` branch had already merged the PR #242 

Example error:
````
[2021-03-06 19:38:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4e8d64722e354aa4c14def7009440c19
Traceback (most recent call last):
  File "/usr/src/app/src/elasticsearch/indexer.py", line 508, in update_index
    transformed = json.dumps(transform(json.loads(doc)))
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 145, in transform
    add_partonomy(doc_copy)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/add_partonomy.py", line 30, in add_partonomy
    ancestor_list = _get_ancestors_of(uri, index)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/add_partonomy.py", line 36, in _get_ancestors_of
    node = index[node_id]
KeyError: 'http://purl.org/sig/ont/fma/fma15828'
````

And a list of uuids that threw this error:
````
[2021-03-06 19:03:19] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 3d2bc79885fc7720f77fddd2c23f02e5
[2021-03-06 19:04:06] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 5f043da4d6347e2b6f93509c000804d1
[2021-03-06 19:04:34] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: d093d6563dad2457356074c3781d9bea
[2021-03-06 19:05:07] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 17cdad1671514b52baaeee599fa06ebf
[2021-03-06 19:05:11] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 39c3c7a6fb9f98c346065eb771febd08
[2021-03-06 19:09:33] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 074c96e0c614d3f8132a60afdd536db4
[2021-03-06 19:09:47] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 960f1766a95573bb5ccd5e45c81a7e1b
[2021-03-06 19:11:07] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 988d21f5795b193ba51a7e00b1574ddf
[2021-03-06 19:11:34] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: f50b8ce55392beae9fa0547a81288f25
[2021-03-06 19:14:03] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4fb887c5b17d203e20143d9044c0bf94
[2021-03-06 19:14:59] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 8d593ea6872956bb98ced0e9b8fda5c8
[2021-03-06 19:15:24] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: ef2f2dc788ae3e63ed9649d69c3ec7f5
[2021-03-06 19:15:57] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 7000456f479ecdd3a5c7f4ba70ada709
[2021-03-06 19:36:01] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 01b0f11f3fc13542c6d837cc47712b85
[2021-03-06 19:36:11] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: ba906793fcba084898ac24e850d5a964
[2021-03-06 19:36:15] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 798978f4efbbbe2d061651bd1460a9c3
[2021-03-06 19:36:23] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 3f431785d52ce16e00102749e5eca384
[2021-03-06 19:36:27] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 84089f9d892b2a3f580d078ce2423656
[2021-03-06 19:36:48] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 191050c2ef9bb9314d0057b48e31ab0d
[2021-03-06 19:36:51] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 7c504503496b18f731a95e844884f591
[2021-03-06 19:37:01] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 2aefc156eeab64b7ca8efc49425f39c0
[2021-03-06 19:37:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: f3f064df9fba093884256bf9f99aacaa
[2021-03-06 19:37:12] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 379708792c96e7679337c17651551950
[2021-03-06 19:37:19] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 32e38bed28499ae00c3b2c45831bc9b4
[2021-03-06 19:37:36] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: eb580ab691158f63336056cbb9920f5b
[2021-03-06 19:37:40] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 5a743beb0514fc5c6d80c58342c645d9
[2021-03-06 19:37:47] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: e639a1b529940388a533ef0124c69ac9
[2021-03-06 19:37:57] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 51cb57b4d8dd205b9c60a9f1daf599f8
[2021-03-06 19:38:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4e8d64722e354aa4c14def7009440c19
````

@mccalluc any insights?

**Comment by mccalluc** [comment]
Can you provide me with the JSON for a document which errors? I may not be looking in the right place... In order to get to the line that throws the error, we need to pass both these checks:
```python
    if 'rui_location' not in doc:
        return
    rui_location = loads(doc['rui_location'])

    if 'ccf_annotations' not in rui_location:
        return
    ccf_annotations = rui_location['ccf_annotations']
```

but taking the first UUID in the list as an example: 
- https://portal.hubmapconsortium.org/browse/sample/4e8d64722e354aa4c14def7009440c19.json does not contain `rui_location`
- https://portal.test.hubmapconsortium.org/browse/sample/4e8d64722e354aa4c14def7009440c19.json is 404, even when logged in.

**Comment by mccalluc** [comment]
@bherr2 -- Assuming a reproducing document can be found, that URI is not what I expect to see. What I expect is something like [this example](https://portal.hubmapconsortium.org/browse/sample/7113f174c5b0da705b126129dff02f80.rui.json):
```
  "ccf_annotations": [
    "http://purl.obolibrary.org/obo/UBERON_0001157"
  ],
```
... and I'm expecting the URI string to match the string in the partonomy-json-ld, where it's all UBERON. Is the data here wrong, or do I need to do more resolve it, or should I skip URIs which don't match, instead of throwing an exception?

**Comment by bherr2** [comment]
Hmm we did have some fma nodes in the partonomy before. I wouldn't assume it's just from Uberon or that the partonomy necessarily has all annotations. But ya I think for your purposes just ignore the nodes you don't recognize. A longer term solution involves looking up the terms using a service a la Jonathon Silverstein's solution.

**Comment by yuanzhou** [comment]
@mccalluc here is the JSON returned from entity-api for 4e8d64722e354aa4c14def7009440c19 which had that error.

````
{
    "created_by_user_displayname": "Marda Jorgensen",
    "created_by_user_email": "marda@ufl.edu",
    "created_by_user_sub": "694c6f6a-1deb-41a6-880f-d1ad8af3705f",
    "created_timestamp": 1614800407532,
    "data_access_level": "consortium",
    "description": "NBF fixed lower 5mm from a 1cm cube collected from against the hilum",
    "direct_ancestor": {
        "created_by_user_displayname": "Marda Jorgensen",
        "created_by_user_email": "marda@ufl.edu",
        "created_by_user_sub": "694c6f6a-1deb-41a6-880f-d1ad8af3705f",
        "created_timestamp": 1614089582575,
        "data_access_level": "consortium",
        "description": "1cm slab through CCF-3",
        "entity_type": "Sample",
        "group_name": "University of Florida TMC",
        "group_uuid": "07a29e4c-ed43-11e8-b56a-0e8017bdda58",
        "hubmap_id": "HBM948.SJCG.773",
        "image_file_metadata": [
            {
                "description": "Section with hilum at top facing up",
                "filepath": "/hive/hubmap/data/uploads/07a29e4c-ed43-11e8-b56a-0e8017bdda58/25f25864816a790ec6868744eef15ec9/HuBMAP 21-010 Spleen CC3 Region (3rd Cut).JPG"
            }
        ],
        "lab_tissue_sample_id": "21-010 Spleen CCF-3",
        "last_modified_timestamp": 1614089582575,
        "organ": "SP",
        "protocol_url": "dx.doi.org/10.17504/protocols.io.bc3kiykw",
        "specimen_type": "organ_piece",
        "submission_id": "UFL0010-SP-3",
        "uuid": "71b342817e4c093c2ba8a4cb7812a285"
    },
    "entity_type": "Sample",
    "group_name": "University of Florida TMC",
    "group_uuid": "07a29e4c-ed43-11e8-b56a-0e8017bdda58",
    "hubmap_id": "HBM237.NWXR.445",
    "lab_tissue_sample_id": "21-010 SP-CC3 Block F",
    "last_modified_timestamp": 1614961892034,
    "last_modified_user_displayname": "Marda Jorgensen",
    "last_modified_user_email": "marda@ufl.edu",
    "last_modified_user_sub": "694c6f6a-1deb-41a6-880f-d1ad8af3705f",
    "organ": "SP",
    "protocol_url": "dx.doi.org/10.17504/protocols.io.bc3kiykw",
    "rui_location": {
        "@context": "https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",
        "@id": "http://purl.org/ccf/1.5/221301ef-b4de-48df-87da-624eeb9dba72",
        "@type": "SpatialEntity",
        "ccf_annotations": [
            "http://purl.org/sig/ont/fma/fma15828",
            "http://purl.org/sig/ont/fma/fma15837",
            "http://purl.obolibrary.org/obo/UBERON_0001248"
        ],
        "creation_date": "2021-03-05",
        "creator": "Marda Jorgensen",
        "creator_first_name": "Marda",
        "creator_last_name": "Jorgensen",
        "dimension_units": "millimeter",
        "placement": {
            "@context": "https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",
            "@id": "http://purl.org/ccf/1.5/221301ef-b4de-48df-87da-624eeb9dba72_placement",
            "@type": "SpatialPlacement",
            "placement_date": "2021-03-05",
            "rotation_order": "XYZ",
            "rotation_units": "degree",
            "scaling_units": "ratio",
            "target": "http://purl.org/ccf/latest/ccf.owl#VHMSpleen",
            "translation_units": "millimeter",
            "x_rotation": 83,
            "x_scaling": 1,
            "x_translation": 32.79,
            "y_rotation": 53,
            "y_scaling": 1,
            "y_translation": 62.571,
            "z_rotation": 5,
            "z_scaling": 1,
            "z_translation": 19.667
        },
        "x_dimension": 10,
        "y_dimension": 10,
        "z_dimension": 5
    },
    "specimen_type": "ffpe_block",
    "submission_id": "UFL0010-SP-3-5",
    "uuid": "4e8d64722e354aa4c14def7009440c19"
}
````

**Comment by mccalluc** [comment]
Thanks! -- I hadn't thought about the current Entities API response being different from what's in the index. Will ignore the IDs which aren't in the partonomy.

**Comment by yuanzhou** [comment]
@bherr2 FYI, on TEST, we are currently using `contains_human_genetic_sequences` as a boolean rather than string "yes"/"no" in both entity-api and search-api. We talked about this before and it seems to be a quick change on your end. Just wanted you know that this has been deployed TEST.

**Comment by bherr2** [comment]
@yuanzhou Yep, we made that change a while back. Thanks!
