### ISSUE TITLE
reindex error on DEV

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#248]
Redeployed the latest code (the same codebase deployed on TEST, but with an eraly copy of PROD neo4j) on DEV and the reindex threw two errors. @jswelling @shirey @mccalluc it looks like something to do with the new antibody stuff, and we don't have these two uuids on TEST at this point. I'm just posting this out in case it's part of the release.

Below are the details of error with uuid 2ba152ceb4f5ab3645b0e5cd2beb3fb1:

```
[2021-03-09 04:14:50] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 2ba152ceb4f5ab3645b0e5cd2beb3fb1
Traceback (most recent call last):
  File "/usr/src/app/src/elasticsearch/indexer.py", line 508, in update_index
    transformed = json.dumps(transform(json.loads(doc)))
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 143, in transform
    sort_files(doc_copy)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/sort_files.py", line 19, in sort_files
    doc['files'].sort(key=lambda file: file['rel_path'].lower())
AttributeError: 'dict' object has no attribute 'sort'
```

The result from entity-api: https://entity-api.dev.hubmapconsortium.org/entities/2ba152ceb4f5ab3645b0e5cd2beb3fb1

<details>

```
{
    "antibodies": [
        {
            "antibody_name": "Anti-CD31 antibody",
            "channel_id": "Cycle2_CH2",
            "conjugated_cat_number": "Akoya 4450017",
            "conjugated_tag": "Akoya BX001-Alexa Fluor 750",
            "dilution": "1/200",
            "lot_number": "B310793     ",
            "rr_id": "AB_1267039",
            "uniprot_accession_number": "P16284"
        },
        {
            "antibody_name": "Anti-CD8a antibody",
            "channel_id": "Cycle2_CH3",
            "conjugated_cat_number": "Akoya 4250012",
            "conjugated_tag": "Akoya BX026-Atto 550",
            "dilution": "1/200",
            "lot_number": "B304054      ",
            "rr_id": "AB_2650657",
            "uniprot_accession_number": "P01732"
        },
        {
            "antibody_name": "Anti-CD20 antibody",
            "channel_id": "Cycle3_CH2",
            "conjugated_cat_number": "Akoya 4450018",
            "conjugated_tag": "Akoya BX007-Alexa Fluor 750",
            "dilution": "1/200",
            "lot_number": "B310936      ",
            "rr_id": "AB_10734340",
            "uniprot_accession_number": "P11836"
        },
        {
            "antibody_name": "Anti-Ki67 antibody",
            "channel_id": "Cycle3_CH3",
            "conjugated_cat_number": "Akoya 4250019",
            "conjugated_tag": "Akoya BX047-Atto 550",
            "dilution": "1/200",
            "lot_number": "B305585    ",
            "rr_id": "AB_396287",
            "uniprot_accession_number": "P46013"
        },
        {
            "antibody_name": "Anti-CD3e antibody",
            "channel_id": "Cycle3_CH4",
            "conjugated_cat_number": "Akoya 4450030",
            "conjugated_tag": "Akoya BX045-Cy5",
            "dilution": "1/200",
            "lot_number": "B320435     ",
            "rr_id": "AB_764498",
            "uniprot_accession_number": "P07766"
        },
        {
            "antibody_name": "Anti-SMA antibody",
            "channel_id": "Cycle4_CH2",
            "conjugated_cat_number": "ab240654",
            "conjugated_tag": "Akoya BX013-Alexa Fluor 750",
            "dilution": "1/200",
            "lot_number": "UF-31Jul2020",
            "rr_id": "AB_2884017",
            "uniprot_accession_number": "P62736"
        },
        {
            "antibody_name": "Anti-Podoplanin antibody",
            "channel_id": "Cycle4_CH3",
            "conjugated_cat_number": "Akoya 4250004",
            "conjugated_tag": "Akoya BX023-Atto 550",
            "dilution": "1/200",
            "lot_number": "B319036     ",
            "rr_id": "AB_1595616",
            "uniprot_accession_number": "Q86YL7"
        },
        {
            "antibody_name": "Anti-CD68 antibody",
            "channel_id": "Cycle4_CH4",
            "conjugated_cat_number": "Akoya 4350019",
            "conjugated_tag": "Akoya BX015-Cy5",
            "dilution": "1/200",
            "lot_number": "B319545      ",
            "rr_id": "AB_11151139",
            "uniprot_accession_number": "P34810"
        },
        {
            "antibody_name": "Anti-PanCK antibody",
            "channel_id": "Cycle5_CH2",
            "conjugated_cat_number": "Akoya 4450020",
            "conjugated_tag": "Akoya BX019-Alexa Fluor 750",
            "dilution": "1/200",
            "lot_number": "B304089     ",
            "rr_id": "AB_2616960",
            "uniprot_accession_number": "P04264"
        },
        {
            "antibody_name": "Anti-CD21 antibody",
            "channel_id": "Cycle5_CH3",
            "conjugated_cat_number": "ab193554",
            "conjugated_tag": "Akoya BX032-Atto 550",
            "dilution": "1/200",
            "lot_number": "UF-21Oct2020",
            "rr_id": "AB_1267035",
            "uniprot_accession_number": "P20023"
        },
        {
            "antibody_name": "Anti-CD4 antibody",
            "channel_id": "Cycle5_CH4",
            "conjugated_cat_number": "Akoya 4350018 ",
            "conjugated_tag": "Akoya BX004-Cy5",
            "dilution": "1/200",
            "lot_number": "B320436    ",
            "rr_id": "AB_2750883",
            "uniprot_accession_number": "P01730"
        },
        {
            "antibody_name": "Anti-Lyve1 antibody",
            "channel_id": "Cycle6_CH2",
            "conjugated_cat_number": "ab232935",
            "conjugated_tag": "Akoya BX004-Alexa Fluor 750",
            "dilution": "1/50",
            "lot_number": "UF-12Feb2020",
            "rr_id": "AB_2884014",
            "uniprot_accession_number": "Q9Y5Y7"
        },
        {
            "antibody_name": "Anti-CD45RO antibody",
            "channel_id": "Cycle6_CH3",
            "conjugated_cat_number": "Akoya 4250023",
            "conjugated_tag": "Akoya BX017-Atto 550",
            "dilution": "1/200",
            "lot_number": "B311690",
            "rr_id": "AB_314418",
            "uniprot_accession_number": "P08575"
        },
        {
            "antibody_name": "Anti-CD11c antibody",
            "channel_id": "Cycle6_CH4",
            "conjugated_cat_number": "Akoya 4350020",
            "conjugated_tag": "Akoya BX024-Cy5",
            "dilution": "1/200",
            "lot_number": "B304058      ",
            "rr_id": "AB_2572997",
            "uniprot_accession_number": "P20702"
        },
        {
            "antibody_name": "Anti-CD35 antibody",
            "channel_id": "Cycle7_CH2",
            "conjugated_cat_number": "ab240961",
            "conjugated_tag": "Akoya BX016-Alexa Fluor 750",
            "dilution": "1/100",
            "lot_number": "UF-14Oct2020",
            "rr_id": "AB_2884017",
            "uniprot_accession_number": "P17927"
        },
        {
            "antibody_name": "Anti-eCAD antibody",
            "channel_id": "Cycle7_CH3",
            "conjugated_cat_number": "Akoya 4250021",
            "conjugated_tag": "Akoya BX014-Atto 550",
            "dilution": "1/200",
            "lot_number": "B317026     ",
            "rr_id": "AB_2533118",
            "uniprot_accession_number": "P12830"
        },
        {
            "antibody_name": "Anti-CD107a antibody",
            "channel_id": "Cycle7_CH4",
            "conjugated_cat_number": "Akoya 4350001",
            "conjugated_tag": "Akoya BX006-Cy5",
            "dilution": "1/200",
            "lot_number": "B319036    ",
            "rr_id": "AB_1134260",
            "uniprot_accession_number": "P11279"
        },
        {
            "antibody_name": "Anti-CD34 antibody",
            "channel_id": "Cycle8_CH2",
            "conjugated_cat_number": "NBP2-32932",
            "conjugated_tag": "Akoya BX022-Alexa Fluor 750",
            "dilution": "1/100",
            "lot_number": "UF-14Oct2020",
            "rr_id": "AB_2861355",
            "uniprot_accession_number": "P28906"
        },
        {
            "antibody_name": "Anti-CD44 antibody",
            "channel_id": "Cycle8_CH3",
            "conjugated_cat_number": "Akoya 4250002",
            "conjugated_tag": "Akoya BX005-Atto 550",
            "dilution": "1/200",
            "lot_number": "B315320     ",
            "rr_id": "AB_312952",
            "uniprot_accession_number": "P16070"
        },
        {
            "antibody_name": "Anti-HLADR antibody",
            "channel_id": "Cycle8_CH4",
            "conjugated_cat_number": "Akoya 4450029",
            "conjugated_tag": "Akoya BX033-Cy5",
            "dilution": "1/200",
            "lot_number": "B292265     ",
            "rr_id": "AB_10563656",
            "uniprot_accession_number": "P04233"
        },
        {
            "antibody_name": "Anti-Foxp3 antibody",
            "channel_id": "Cycle9_CH3",
            "conjugated_cat_number": "14-4777-82",
            "conjugated_tag": "Akoya BX020-Atto 550",
            "dilution": "1/50",
            "lot_number": "UF-12Feb2020",
            "rr_id": "AB_467556",
            "uniprot_accession_number": "Q9BZS1"
        },
        {
            "antibody_name": "Anti-CD163 antibody",
            "channel_id": "Cycle9_CH4",
            "conjugated_cat_number": "NBI10-40686",
            "conjugated_tag": "Akoya BX036-Cy5",
            "dilution": "1/200",
            "lot_number": "UF-03Aug2020",
            "rr_id": "AB_714951",
            "uniprot_accession_number": "Q86VB7"
        },
        {
            "antibody_name": "Anti-COL4 antibody",
            "channel_id": "Cycle10_CH3",
            "conjugated_cat_number": "ab226485",
            "conjugated_tag": "Akoya BX029-Atto 550",
            "dilution": "1/200",
            "lot_number": "UF-03Aug2020",
            "rr_id": "AB_2801511",
            "uniprot_accession_number": "P02462"
        },
        {
            "antibody_name": "Anti-Vimentin antibody",
            "channel_id": "Cycle10_CH4",
            "conjugated_cat_number": "ab8978",
            "conjugated_tag": "Akoya BX042-Cy5",
            "dilution": "1/400",
            "lot_number": "UF-31Jul2020",
            "rr_id": "AB_306907",
            "uniprot_accession_number": "P08670"
        },
        {
            "antibody_name": "Anti-CD15 antibody",
            "channel_id": "Cycle11_CH3",
            "conjugated_cat_number": "559045",
            "conjugated_tag": "Akoya BX035-Atto 550",
            "dilution": "1/200",
            "lot_number": "UF-14Oct2020",
            "rr_id": "AB_397181",
            "uniprot_accession_number": "P22083"
        },
        {
            "antibody_name": "Anti-CD45 antibody",
            "channel_id": "Cycle11_CH4",
            "conjugated_cat_number": "14-9457-82",
            "conjugated_tag": "Akoya BX027-Cy5",
            "dilution": "1/100",
            "lot_number": "UF-13Oct2020",
            "rr_id": "AB_11063696",
            "uniprot_accession_number": "P08575"
        },
        {
            "antibody_name": "Anti-CD5 antibody",
            "channel_id": "Cycle12_CH3",
            "conjugated_cat_number": "ab213003",
            "conjugated_tag": "Akoya BX041-Atto 550",
            "dilution": "1/200",
            "lot_number": "UF-13Oct2020",
            "rr_id": "AB_2884016",
            "uniprot_accession_number": "P06127"
        },
        {
            "antibody_name": "Anti-CD1c antibody",
            "channel_id": "Cycle12_CH4",
            "conjugated_cat_number": "ab270797",
            "conjugated_tag": "Akoya BX-30-Cy5",
            "dilution": "1/100",
            "lot_number": "UF-21Oct2020",
            "rr_id": "AB_2884015",
            "uniprot_accession_number": "P29017"
        }
    ],
    "contains_human_genetic_sequences": false,
    "contributors": [
        {
            "affiliation": "TMC-Florida/Zurich",
            "first_name": "Mark",
            "last_name": "Atkinson",
            "middle_name_or_initial": "A",
            "name": "Mark Atkinson",
            "orcid_id": "0000-0001-8489-4782"
        },
        {
            "affiliation": "TMC-Florida/Zurich",
            "first_name": "Jerelyn",
            "last_name": "Nick",
            "middle_name_or_initial": "A",
            "name": "Jerelyn Nick",
            "orcid_id": "0000-0002-8928-741X"
        },
        {
            "affiliation": "TMC-Florida/Zurich",
            "first_name": "Marda",
            "last_name": "Jorgensen",
            "middle_name_or_initial": "L",
            "name": "Marda Jorgenson",
            "orcid_id": "0000-0002-7250-3569"
        },
        {
            "affiliation": "TMC-Florida/Zurich",
            "first_name": "Hunter",
            "last_name": "Hakimian",
            "middle_name_or_initial": "B",
            "name": "Hunter Hakimian",
            "orcid_id": "0000-0001-9668-044X"
        },
        {
            "affiliation": "TMC-Florida/Zurich",
            "first_name": "Clive",
            "last_name": "Wasserfall",
            "middle_name_or_initial": "H",
            "name": "Clive Wasserman",
            "orcid_id": "0000-0002-3522-8932"
        }
    ],
    "created_by_user_displayname": "Bill Shirey",
    "created_by_user_email": "SHIREY@pitt.edu",
    "created_by_user_sub": "e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
    "created_timestamp": 1615153115883,
    "data_access_level": "consortium",
    "data_types": [
        "CODEX"
    ],
    "direct_ancestors": [
        {
            "created_by_user_displayname": "Bill Shirey",
            "created_by_user_email": "SHIREY@pitt.edu",
            "created_by_user_sub": "e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
            "created_timestamp": 1614632083232,
            "data_access_level": "consortium",
            "description": "Joe updated timestamp4",
            "entity_type": "Sample",
            "group_name": "IEC Testing Group",
            "group_uuid": "5bd084c8-edc2-11e8-802f-0e368f3075e8",
            "hubmap_id": "HBM872.DMSB.824",
            "lab_tissue_sample_id": "bio-3-tst",
            "last_modified_timestamp": 1614632083232,
            "last_modified_user_displayname": "Bill Shirey",
            "last_modified_user_email": "SHIREY@pitt.edu",
            "last_modified_user_sub": "e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
            "organ": "SI",
            "specimen_type": "biopsy",
            "submission_id": "STAN0004-SI-6",
            "uuid": "ef64753b7eb4622c06d1c3935e9635f9",
            "visit": "3"
        }
    ],
    "entity_type": "Dataset",
    "group_name": "IEC Testing Group",
    "group_uuid": "5bd084c8-edc2-11e8-802f-0e368f3075e8",
    "hubmap_id": "HBM666.XWKC.743",
    "ingest_metadata": {
        "dag_provenance_list": [
            {
                "hash": "360bc1e",
                "origin": "https://github.com/hubmapconsortium/ingest-pipeline.git"
            }
        ],
        "extra_metadata": {
            "collectiontype": "generic_metadatatsv"
        },
        "files": {
            "B": "fb",
            "a": "fa"
        },
        "metadata": {
            "BILLTEST": "TEST VALUE",
            "acquisition_instrument_model": "BZ-X800",
            "acquisition_instrument_vendor": "Keyence",
            "analyte_class": "protein",
            "antibodies_path": "extras/UFLA_antibodies_121120.tsv",
            "assay_category": "imaging",
            "assay_type": "CODEX",
            "contributors_path": "extras/UFLA_CODEX_contributors.tsv",
            "data_path": ".",
            "donor_id": "UFL0003",
            "execution_datetime": "2020-11-02 12:54",
            "is_targeted": "TRUE",
            "number_of_antibodies": "28",
            "number_of_channels": "4",
            "number_of_cycles": "13",
            "operator": "Marda Jorgensen",
            "operator_email": "marda@ufl.edu",
            "pi": "Clive Wasserfall",
            "pi_email": "clive@ufl.edu",
            "preparation_instrument_model": "version 1 robot",
            "preparation_instrument_vendor": "CODEX",
            "protocols_io_doi": "10.17504/protocols.io.bdcbi2sn",
            "reagent_prep_protocols_io_doi": "10.17504/protocols.io.bc2riyd7",
            "resolution_x_unit": "nm",
            "resolution_x_value": "377.4038462",
            "resolution_y_unit": "nm",
            "resolution_y_value": "377.4038462",
            "resolution_z_unit": "nm",
            "resolution_z_value": "1500",
            "section_prep_protocols_io_doi": "10.17504/protocols.io.bbsdina7",
            "tissue_id": "UFL0003-LY01-1-1"
        }
    },
    "last_modified_timestamp": 1615153448175,
    "last_modified_user_displayname": "Bill Shirey",
    "last_modified_user_email": "SHIREY@pitt.edu",
    "last_modified_user_sub": "e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
    "local_directory_rel_path": "consortium/IEC Testing Group/2ba152ceb4f5ab3645b0e5cd2beb3fb1/",
    "pipeline_message": "the process ran",
    "status": "QA",
    "title": "BILL TESTING 355",
    "uuid": "2ba152ceb4f5ab3645b0e5cd2beb3fb1"
}
```

</details>

The other similar error is for uuid 265c57a536c4572492df1c86209283bd.

**Comment by mccalluc** [comment]
The doctest for the function that's failing:
```
    >>> doc = {
    ...    'files': [
    ...         {'rel_path': './B.txt', 'capitals': 'sorted correctly'},
    ...         {'rel_path': './a.txt'},
    ...         {'rel_path': './c.txt'}
    ...     ]
    ... }
    >>> sort_files(doc)
    >>> pprint(doc)
    {'files': [{'rel_path': './a.txt'},
               {'capitals': 'sorted correctly', 'rel_path': './B.txt'},
               {'rel_path': './c.txt'}]}
 ```
Two things are strange: 
- This function should only be operating on `files` at the top level of the document, and that's not the case in your example, which has 
```
...
    "ingest_metadata": {
        ...
        "files": {
            "B": "fb",
            "a": "fa"
        },
...
```
- This looks strange: Is it just mock data? If this `files` is the same as the `files` the code is running on, it should be a list, not a dict.

Possible next steps:
- Provide a reproducer I can run locally. (@yuanzhou ?)
- Clarify the semantics of this `files`... should it conform to the earlier structure, or is it something new? (@jswelling ?)
- Look through the history of this code, and understand why this was introduced, and see if there are datasets which use it now. (me)

**Comment by shirey** [comment]
@yuanzhou *ingest_metadata* is supposed to be converted to *metadata* for the indices.  Per https://github.com/hubmapconsortium/search-api/blob/5c35b6068c57240413160bb15bc431420e45ff8d/src/elasticsearch/neo4j-to-es-attributes.json#L75-L77

**Comment by shirey** [comment]
@yuanzhou @mccalluc What I see above is some scratch test data that I've added, you shouldn't be paying attention to it.  Sorry for any confusion there.

**Comment by mccalluc** [comment]
@yuanzhou -- If it's possible, I would still like to be able to locally reproduce the error you saw. If it's really moot, ok, but it would be good for me to understand what is different about the invocation in the two environments.

**Comment by yuanzhou** [comment]
@mccalluc sure thing. I just reopened this issue. Let me just reindex these two entities individually and see if I could reproduce the errors. The errors I found were from the full reindex output. Then I'll send you the details of this reproducer. Can you explain a bit more about this "reproducer"? In case I'm thinking something else.

**Comment by mccalluc** [comment]
@yuanzhou : By local reproducer, I mean I expect to see the same error when I run
```
PYTHONPATH="src:$PYTHONPATH"   python src/elasticsearch/addl_index_transformations/portal/__init__.py   /tmp/bad-doc.json
```

**Comment by yuanzhou** [comment]
No longer an issue with updated PROD database copy.
