### ISSUE TITLE
reindex error during doc transformation

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#250]
Attached is  one of the json docs to be transformed that caused the error. The reindex target is sample 7e3cb6be065ddb2c968309e8dc2f0d29 .

````
[2021-03-11 15:11:12] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 38f86ebcefab20e77bab474529999a6e
Traceback (most recent call last):
  File "/usr/src/app/src/elasticsearch/indexer.py", line 512, in update_index
    transformed = json.dumps(transform(json.loads(doc)))
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 137, in transform
    _clean(doc_copy)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 160, in _clean
    _map(doc, _simple_clean)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 171, in _map
    _map(fragment, clean)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 171, in _map
    _map(fragment, clean)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 166, in _map
    clean(doc)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 183, in _simple_clean
    if field in doc and doc[field] == 'daniel Cotter':
TypeError: argument of type 'NoneType' is not iterable
````

[doc.json.txt](https://github.com/hubmapconsortium/search-api/files/6124728/doc.json.txt)

**Comment by yuanzhou** [comment]
Fixed https://github.com/hubmapconsortium/search-api/commit/020e67f33183d131674205d85e193ccfb27809b1
