### ISSUE TITLE
Entity not being indexed correctly

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#365]
The Vanderbilt entity isn't being indexed correctly:
5ce2a8be2c804a4d7a73dc3b01911aad

**Comment by yuanzhou** [comment]
Error during reindex:
```
[2021-09-06 18:20:42] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 5ce2a8be2c804a4d7a73dc3b01911aad
Traceback (most recent call last):
  File "./elasticsearch/indexer.py", line 767, in update_index
    transformed = json.dumps(transform(json.loads(doc)))
  File "./elasticsearch/addl_index_transformations/portal/__init__.py", line 136, in transform
    translate(doc_copy)
  File "./elasticsearch/addl_index_transformations/portal/translate.py", line 25, in translate
    _translate_data_type(doc)
  File "./elasticsearch/addl_index_transformations/portal/translate.py", line 228, in _translate_data_type
    _map(doc, 'data_types', _data_types_map)
  File "./elasticsearch/addl_index_transformations/portal/translate.py", line 40, in _map
    doc[f'mapped_{key}'] = map(doc[key])
  File "./elasticsearch/addl_index_transformations/portal/translate.py", line 233, in _data_types_map
    f"Maximum 2 types, and one should be image pyramid: {ks}"
AssertionError: Maximum 2 types, and one should be image pyramid: ['AF', 'MALDI-IMS-neg', 'MALDI-IMS-pos', 'PAS']
```

@mccalluc looks like the translate code at https://github.com/hubmapconsortium/search-api/blob/test-release/src/elasticsearch/addl_index_transformations/portal/translate.py#L231 requires the dataset to have at maximum only two data types.  I don't quite understand why "one should be image pyramid" at the same time. Can you share your knowledge on this and give some suggestions on how to address such issue? Thanks.

**Comment by mccalluc** [comment]
The incoming data is bad, or at least not what we expect. It's not ideal that we're representing the assay type as an array: a more clear structure would be a single field for the type, and a boolean flag if this is a derived image pyramid.

I'd suggest following up with ... Joel? It's always possible that we need to do something new, but having multiple types on an assay would be a very big, very disruptive change.

**Comment by shirey** [comment]
Closing this, no fix needed.  We won't allow this many data types and Kevin said that Vanderbilt will re-register this data.
