### ISSUE TITLE
Using secret key on search-api throws 500 errors

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#536]
The following throws a 500
```
curl --location --request POST 'https://search-api.test.hubmapconsortium.org/search' \
--header 'Authorization: Bearer <secret key>' \
--header 'Content-Type: application/json' \
--data-raw '{"query":{"ids":{"values":["5b49daaa47a8d293d2765b31b95120f1"]}}}'
```
From the logs:
```
[2022-07-13 18:11:50] INFO in app:202: ======search with no index provided======
[2022-07-13 18:11:50] INFO in app:203: default_index: entities
[2022-07-13 18:11:50] INFO in app:597: ======user_info======
[2022-07-13 18:11:50] INFO in app:598: {'username': 'hubmap@hubmapconsortium.org', 'token_type': 'Bearer', 'client_id': '21f293b0-5fa5-4ee1-9e0e-3cf88bd70114', 'scope': 'process', 'active': True, 'is_system_account': True, 'nbf': 9999999999, 'name': 'HuBMAP Process', 'aud': ['proc.role', '3e7bce63-129d-33d0-8f6c-834b34cd382e'], 'sub': '3e7bce63-129d-33d0-8f6c-834b34cd382e', 'iss': 'https://auth.hubmapconsortium.org', 'exp': 9999999999, 'iat': 9999999999, 'email': 'hubmap@hubmapconsortium.org', 'hmgroupids': ['5777527e-ec11-11e8-ab41-0af86edb4424', '07a29e4c-ed43-11e8-b56a-0e8017bdda58', '308f5ffc-ed43-11e8-b56a-0e8017bdda58', '73bb26e4-ed43-11e8-8f19-0a7c1eab007a', 'def5fd76-ed43-11e8-b56a-0e8017bdda58', '03b3d854-ed44-11e8-8bce-0e368f3075e8', '9c4a56ca-79ac-11ea-8359-0e41da796b5d', '5c106f29-ea2d-11e9-85e8-0efb3ba9a670', '76755cd8-79ad-11ea-8293-0a53601d30b5', 'f5af3a5a-e93c-11e9-8559-0efb3ba9a670', 'ab7db177-79ad-11ea-835a-0e41da796b5d', 'ca46f893-79ad-11ea-b66c-0a990c2810ad', 'eb5c5345-79ad-11ea-bc85-0ef992ed7ca1', 'f677f31f-79b0-11ea-8295-0a53601d30b5', '2cf25858-ed44-11e8-991d-0e368f3075e8', '5bd084c8-edc2-11e8-802f-0e368f3075e8', '89a69625-99d7-11ea-9366-0e98982705c1', 'ee6f749f-c86f-11eb-b35e-4dfdb5d10392', '0b8ca9fe-c870-11eb-b35e-4dfdb5d10392', '301615f9-c870-11eb-a8dc-35ce3d8786fe', '1fe64d24-c870-11eb-9a03-a9c8d5e16226', '69cb89c4-c870-11eb-b360-4dfdb5d10392', '878a6a26-c870-11eb-a8dc-35ce3d8786fe', '972b2a76-c870-11eb-a8dc-35ce3d8786fe', 'b148f323-c870-11eb-b360-4dfdb5d10392', 'd62c4872-c870-11eb-a8dd-35ce3d8786fe', 'ea9a6442-c870-11eb-bf37-f92c084a680e', '177f92c0-c871-11eb-9a04-a9c8d5e16226'], 'hmscopes': ['process']}
[2022-07-13 18:11:50] ERROR in app:1891: Exception on /search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/src/search-adaptor/src/app.py", line 71, in __search
    return self.search()
  File "/usr/src/app/src/search-adaptor/src/app.py", line 207, in search
    target_index = self.get_target_index(request, self.DEFAULT_INDEX_WITHOUT_PREFIX)
  File "/usr/src/app/src/search-adaptor/src/app.py", line 609, in get_target_index
    if self.GLOBUS_HUBMAP_READ_GROUP_UUID in user_info[self.GROUP_ID]:
KeyError: 'group_membership_ids'
[pid: 50|app: 0|req: 290/3070] 172.31.8.129 () {54 vars in 897 bytes} [Wed Jul 13 18:11:50 2022] POST /search => generated 194 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 91 bytes (1 switches on core 0)
```

**Comment by yuanzhou** [comment]
Also had to upgrade the version in search-adaptor via https://github.com/dbmi-pitt/search-adaptor/pull/5 to address dependency conflicts during build
