### ISSUE TITLE
Finalize full reindex procedure

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#895]
- Update the step-by-step guide in both README.md and the script `help` instructions
- Remove misleading print outputs at the end of each command run
- Add a new command to delete those `flushYYYYMMDD_fresh_index_*` indices AFTER `catch-up`

**Comment by yuanzhou** [comment]
1/9/2025 

`go-live` warning:
```
[2025-01-09 12:44:55] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): raw.githubusercontent.com:443
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
  ```
 

`catch-up` error

```
[2025-01-09 12:45:58] INFO in hubmap_translator:661: Unable to find 'entities' transformer, indexing documents untransformed.
[2025-01-09 12:45:58] ERROR in hubmap_translator:1369: Encountered exception e=local variable 'private_doc' referenced before assignment executing _call_indexer() with uuid: b1ed06d9475673e6e41c324b0a998eab, entity_type: Upload
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1361, in _call_indexer
    self._transform_and_write_entity_to_index_group(entity=entity
  File "/usr/src/app/src/hubmap_translator.py", line 662, in _transform_and_write_entity_to_index_group
    docs_to_write_dict[self.index_group_es_indices[index_group]['private']] = private_doc
UnboundLocalError: local variable 'private_doc' referenced before assignment
```

**Comment by yuanzhou** [comment]
3/5/2025 PROD `go-live`

```
[2025-03-05 13:20:00] DEBUG in connectionpool:474: https://search-hubmap-prod-e6jfsykycntlyd7m5khviqfbpi.us-east-1.es.amazonaws.com:443 "PUT /fill20250304_fresh_index_hm_prod_consortium_portal/_clone/hm_prod_consortium_portal HTTP/1.1" 400 189
[2025-03-05 13:20:00] ERROR in es_manager:263: Failed to clone source index: fill20250304_fresh_index_hm_prod_consortium_portal  to target index: hm_prod_consortium_portal.
[2025-03-05 13:20:00] ERROR in es_manager:265: Error Payload: {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [hm_prod_consortium_portal/PCbAv21yTjuuf0501ONwVw] already exists","index_uuid":"PCbAv21yTjuuf0501ONwVw","index":"hm_prod_consortium_portal"}],"type":"resource_already_exists_exception","reason":"index [hm_prod_consortium_portal/PCbAv21yTjuuf0501ONwVw] already exists","index_uuid":"PCbAv21yTjuuf0501ONwVw","index":"hm_prod_consortium_portal"},"status":400}
Traceback (most recent call last):
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 745, in <module>
    swap_index_names_per_strategy(es_mgr=esmanager
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 383, in swap_index_names_per_strategy
    es_mgr.clone_index(source_index_name=destination_index
  File "/usr/src/app/scripts/fresh_indices/es_manager.py", line 267, in clone_index
    raise Exception(f"Failed to clone source index: {source_index_name} "
Exception: Failed to clone source index: fill20250304_fresh_index_hm_prod_consortium_portal  to target index: hm_prod_consortium_portal with status_code-400, reason-index [hm_prod_consortium_portal/PCbAv21yTjuuf0501ONwVw] already exists. See logs.
```

**Comment by yuanzhou** [comment]
4/23/2025, `catch-up` on TEST after `go-live`:
```
[2025-04-23 03:57:21] INFO in fresh_indices:562: The set of UUIDs for entities to re-index is {'4a2b53b9e91741e137966501292632f7', '85479528b4dcb4b0b4631f439de04c22'}
[2025-04-23 03:57:21] DEBUG in fresh_indices:565:  reindex 4a2b53b9e91741e137966501292632f7
[2025-04-23 03:57:21] INFO in hubmap_translator:1184: Start executing reindex_entity() on uuid: 4a2b53b9e91741e137966501292632f7
[2025-04-23 03:57:21] INFO in hubmap_translator:1871: Start executing call_entity_api() on uuid: 4a2b53b9e91741e137966501292632f7
[2025-04-23 03:57:21] DEBUG in connectionpool:246: Starting new HTTP connection (1): entity-api:8080
[2025-04-23 03:57:21] DEBUG in connectionpool:474: http://entity-api:8080 "GET /documents/4a2b53b9e91741e137966501292632f7 HTTP/1.1" 200 456
[2025-04-23 03:57:21] INFO in hubmap_translator:1901: Finished executing call_entity_api() on uuid: 4a2b53b9e91741e137966501292632f7
[2025-04-23 03:57:21] INFO in hubmap_translator:1356: Start executing _call_indexer() on uuid: 4a2b53b9e91741e137966501292632f7, entity_type: Upload
[2025-04-23 03:57:21] INFO in hubmap_translator:626: Start executing direct 'entities' updates for entity['uuid']=4a2b53b9e91741e137966501292632f7, entity['entity_type']=Upload
[2025-04-23 03:57:21] INFO in hubmap_translator:1552: Start executing _generate_doc() for Upload of uuid: 4a2b53b9e91741e137966501292632f7 for the entities index group.
[2025-04-23 03:57:21] ERROR in hubmap_translator:1739: Exceptions during executing hubmap_translator._generate_doc()
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1676, in _generate_doc
    entity['ancestors'] = self._relatives_for_index_group(  relative_ids=ancestor_ids
UnboundLocalError: local variable 'ancestor_ids' referenced before assignment
[2025-04-23 03:57:21] ERROR in hubmap_translator:648: Exception document generation for uuid: 4a2b53b9e91741e137966501292632f7, entity_type: Upload for 'entities' reindex caused 'local variable 'ancestor_ids' referenced before assignment'
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1676, in _generate_doc
    entity['ancestors'] = self._relatives_for_index_group(  relative_ids=ancestor_ids
UnboundLocalError: local variable 'ancestor_ids' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 635, in _transform_and_write_entity_to_index_group
    private_doc = self._generate_doc(   entity=doc_entity
  File "/usr/src/app/src/hubmap_translator.py", line 1742, in _generate_doc
    raise Exception(e)
Exception: local variable 'ancestor_ids' referenced before assignment
[2025-04-23 03:57:21] ERROR in hubmap_translator:651: For Upload 4a2b53b9e91741e137966501292632f7, failed to generate document for consortium indices.
[2025-04-23 03:57:21] INFO in hubmap_translator:661: Unable to find 'entities' transformer, indexing documents untransformed.
[2025-04-23 03:57:21] ERROR in hubmap_translator:1369: Encountered exception e=local variable 'private_doc' referenced before assignment executing _call_indexer() with uuid: 4a2b53b9e91741e137966501292632f7, entity_type: Upload
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1361, in _call_indexer
    self._transform_and_write_entity_to_index_group(entity=entity
  File "/usr/src/app/src/hubmap_translator.py", line 662, in _transform_and_write_entity_to_index_group
    docs_to_write_dict[self.index_group_es_indices[index_group]['private']] = private_doc
UnboundLocalError: local variable 'private_doc' referenced before assignment
[2025-04-23 03:57:21] INFO in hubmap_translator:1189: Finished executing reindex_entity() on uuid: 4a2b53b9e91741e137966501292632f7
```

**Comment by yuanzhou** [comment]
5/5/2025 TEST, `go-live` failed
```
[2025-05-05 11:51:49] INFO in fresh_indices:318: ############# Swapping index names to go live via script started at 11:51:49 #############
[2025-05-05 11:51:49] INFO in fresh_indices:320: Swapping index names for create_fill.
[2025-05-05 11:51:49] INFO in fresh_indices:327: Plan to swap hm_test_public_entities to become flush20250504_fresh_index_hm_test_public_entities and swap fill20250504_fresh_index_hm_test_public_entities to become hm_test_public_entities
[2025-05-05 11:51:49] INFO in fresh_indices:327: Plan to swap hm_test_consortium_entities to become flush20250504_fresh_index_hm_test_consortium_entities and swap fill20250504_fresh_index_hm_test_consortium_entities to become hm_test_consortium_entities
[2025-05-05 11:51:49] INFO in fresh_indices:327: Plan to swap hm_test_public_portal to become flush20250504_fresh_index_hm_test_public_portal and swap fill20250504_fresh_index_hm_test_public_portal to become hm_test_public_portal
[2025-05-05 11:51:49] INFO in fresh_indices:327: Plan to swap hm_test_consortium_portal to become flush20250504_fresh_index_hm_test_consortium_portal and swap fill20250504_fresh_index_hm_test_consortium_portal to become hm_test_consortium_portal
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /hm_test_public_entities HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /flush20250504_fresh_index_hm_test_public_entities HTTP/1.1" 404 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /fill20250504_fresh_index_hm_test_public_entities HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /hm_test_consortium_entities HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /flush20250504_fresh_index_hm_test_consortium_entities HTTP/1.1" 404 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /fill20250504_fresh_index_hm_test_consortium_entities HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /hm_test_public_portal HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /flush20250504_fresh_index_hm_test_public_portal HTTP/1.1" 404 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /fill20250504_fresh_index_hm_test_public_portal HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /hm_test_consortium_portal HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /flush20250504_fresh_index_hm_test_consortium_portal HTTP/1.1" 404 0
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "HEAD /fill20250504_fresh_index_hm_test_consortium_portal HTTP/1.1" 200 0
[2025-05-05 11:51:49] DEBUG in fresh_indices:353: Set write block on source_index=hm_test_public_entities.
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "PUT /hm_test_public_entities/_block/write HTTP/1.1" 200 109
[2025-05-05 11:51:49] INFO in es_manager:236: Set 'write' block on index: hm_test_public_entities
[2025-05-05 11:51:49] DEBUG in fresh_indices:356: Set write block on destination_index=fill20250504_fresh_index_hm_test_public_entities.
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "PUT /fill20250504_fresh_index_hm_test_public_entities/_block/write HTTP/1.1" 200 128
[2025-05-05 11:51:49] INFO in es_manager:236: Set 'write' block on index: fill20250504_fresh_index_hm_test_public_entities
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:49] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "GET /_cluster/health/hm_test_public_entities?wait_for_status=green&timeout=30s HTTP/1.1" 200 263
[2025-05-05 11:51:49] DEBUG in es_manager:291: Wait for index: hm_test_public_entities to reach "green" health complete.
[2025-05-05 11:51:49] DEBUG in fresh_indices:362: Health of source_index=hm_test_public_entities is green.
[2025-05-05 11:51:49] DEBUG in fresh_indices:365: Clone source_index=hm_test_public_entities to flush_index=flush20250504_fresh_index_hm_test_public_entities.
[2025-05-05 11:51:49] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:50] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "PUT /hm_test_public_entities/_clone/flush20250504_fresh_index_hm_test_public_entities HTTP/1.1" 200 108
[2025-05-05 11:51:50] INFO in es_manager:261: Cloned source index: hm_test_public_entities to target index: flush20250504_fresh_index_hm_test_public_entities
[2025-05-05 11:51:50] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:53] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "GET /_cluster/health/flush20250504_fresh_index_hm_test_public_entities?wait_for_status=green&timeout=30s HTTP/1.1" 200 265
[2025-05-05 11:51:53] DEBUG in es_manager:291: Wait for index: flush20250504_fresh_index_hm_test_public_entities to reach "green" health complete.
[2025-05-05 11:51:53] DEBUG in fresh_indices:372: Health of flush_index=flush20250504_fresh_index_hm_test_public_entities is green.
[2025-05-05 11:51:53] DEBUG in fresh_indices:373: Set none block on source_index=hm_test_public_entities.
[2025-05-05 11:51:53] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:53] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "PUT /hm_test_public_entities/_settings HTTP/1.1" 200 47
[2025-05-05 11:51:53] INFO in es_manager:236: Set 'none' block on index: hm_test_public_entities
[2025-05-05 11:51:53] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:53] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "DELETE /hm_test_public_entities HTTP/1.1" 400 231
[2025-05-05 11:51:53] ERROR in es_manager:146: Failed to delete index: hm_test_public_entities in elasticsearch.
[2025-05-05 11:51:53] ERROR in es_manager:147: Error Message: {"error":{"root_cause":[{"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[hm_test_public_entities/Ad_zVPrpTbqFxrvai6YkWw]]. Try again after snapshot finishes or cancel the currently running snapshot."}],"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[hm_test_public_entities/Ad_zVPrpTbqFxrvai6YkWw]]. Try again after snapshot finishes or cancel the currently running snapshot."},"status":400}
[2025-05-05 11:51:53] DEBUG in fresh_indices:377: Deleted source_index=hm_test_public_entities.
[2025-05-05 11:51:53] DEBUG in fresh_indices:382: Clone destination_index=fill20250504_fresh_index_hm_test_public_entities to source_index=hm_test_public_entities.
[2025-05-05 11:51:53] DEBUG in connectionpool:1021: Starting new HTTPS connection (1): search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443
[2025-05-05 11:51:53] DEBUG in connectionpool:474: https://search-hubmap-dev-test-hfnqv4ylo5ywvc42vwnyptbup4.us-east-1.es.amazonaws.com:443 "PUT /fill20250504_fresh_index_hm_test_public_entities/_clone/hm_test_public_entities HTTP/1.1" 400 188
[2025-05-05 11:51:53] ERROR in es_manager:263: Failed to clone source index: fill20250504_fresh_index_hm_test_public_entities  to target index: hm_test_public_entities.
[2025-05-05 11:51:53] ERROR in es_manager:265: Error Payload: {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [hm_test_public_entities/Ad_zVPrpTbqFxrvai6YkWw] already exists","index_uuid":"Ad_zVPrpTbqFxrvai6YkWw","index":"hm_test_public_entities"}],"type":"resource_already_exists_exception","reason":"index [hm_test_public_entities/Ad_zVPrpTbqFxrvai6YkWw] already exists","index_uuid":"Ad_zVPrpTbqFxrvai6YkWw","index":"hm_test_public_entities"},"status":400}
Traceback (most recent call last):
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 745, in <module>
    swap_index_names_per_strategy(es_mgr=esmanager
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 383, in swap_index_names_per_strategy
    es_mgr.clone_index(source_index_name=destination_index
  File "/usr/src/app/scripts/fresh_indices/es_manager.py", line 267, in clone_index
    raise Exception(f"Failed to clone source index: {source_index_name} "
Exception: Failed to clone source index: fill20250504_fresh_index_hm_test_public_entities  to target index: hm_test_public_entities with status_code-400, reason-index [hm_test_public_entities/Ad_zVPrpTbqFxrvai6YkWw] already exists. See logs.
[root@search-api fresh_indices]# ./fresh_indices.sh go-live
Command to execute: 'go-live'
Output will be in ./exec_info

```

**Comment by yuanzhou** [comment]
5/14/2025, PROD `catch-up`

```
[2025-05-14 12:23:35] DEBUG in connectionpool:474: http://entity-api:8080 "GET /documents/98fbcbd41c18297a31693065c4cb07c8 HTTP/1.1" 200 19690
[2025-05-14 12:23:35] INFO in hubmap_translator:1901: Finished executing call_entity_api() on uuid: 98fbcbd41c18297a31693065c4cb07c8
[2025-05-14 12:23:35] INFO in hubmap_translator:1356: Start executing _call_indexer() on uuid: 98fbcbd41c18297a31693065c4cb07c8, entity_type: Upload
[2025-05-14 12:23:35] INFO in hubmap_translator:626: Start executing direct 'entities' updates for entity['uuid']=98fbcbd41c18297a31693065c4cb07c8, entity['entity_type']=Upload
[2025-05-14 12:23:35] INFO in hubmap_translator:1552: Start executing _generate_doc() for Upload of uuid: 98fbcbd41c18297a31693065c4cb07c8 for the entities index group.
[2025-05-14 12:23:35] ERROR in hubmap_translator:1739: Exceptions during executing hubmap_translator._generate_doc()
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1676, in _generate_doc
    entity['ancestors'] = self._relatives_for_index_group(  relative_ids=ancestor_ids
UnboundLocalError: local variable 'ancestor_ids' referenced before assignment
[2025-05-14 12:23:35] ERROR in hubmap_translator:648: Exception document generation for uuid: 98fbcbd41c18297a31693065c4cb07c8, entity_type: Upload for 'entities' reindex caused 'local variable 'ancestor_ids' referenced before assignment'
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1676, in _generate_doc
    entity['ancestors'] = self._relatives_for_index_group(  relative_ids=ancestor_ids
UnboundLocalError: local variable 'ancestor_ids' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 635, in _transform_and_write_entity_to_index_group
    private_doc = self._generate_doc(   entity=doc_entity
  File "/usr/src/app/src/hubmap_translator.py", line 1742, in _generate_doc
    raise Exception(e)
Exception: local variable 'ancestor_ids' referenced before assignment
[2025-05-14 12:23:35] ERROR in hubmap_translator:651: For Upload 98fbcbd41c18297a31693065c4cb07c8, failed to generate document for consortium indices.
[2025-05-14 12:23:35] INFO in hubmap_translator:661: Unable to find 'entities' transformer, indexing documents untransformed.
[2025-05-14 12:23:35] ERROR in hubmap_translator:1369: Encountered exception e=local variable 'private_doc' referenced before assignment executing _call_indexer() with uuid: 98fbcbd41c18297a31693065c4cb07c8, entity_type: Upload
Traceback (most recent call last):
  File "/usr/src/app/src/hubmap_translator.py", line 1361, in _call_indexer
    self._transform_and_write_entity_to_index_group(entity=entity
  File "/usr/src/app/src/hubmap_translator.py", line 662, in _transform_and_write_entity_to_index_group
    docs_to_write_dict[self.index_group_es_indices[index_group]['private']] = private_doc
UnboundLocalError: local variable 'private_doc' referenced before assignment
```

**Comment by yuanzhou** [comment]
5/17/2025, PROD full reindex over the weekend
`go-live` failed:
```
[2025-05-18 03:38:51] DEBUG in connectionpool:474: https://search-hubmap-prod-e6jfsykycntlyd7m5khviqfbpi.us-east-1.es.amazonaws.com:443 "PUT /fill20250517_fresh_index_hm_prod_consortium_entities/_clone/hm_prod_consortium_entities HTTP/1.1" 500 193
[2025-05-18 03:38:51] ERROR in es_manager:263: Failed to clone source index: fill20250517_fresh_index_hm_prod_consortium_entities  to target index: hm_prod_consortium_entities.
[2025-05-18 03:38:51] ERROR in es_manager:265: Error Payload: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"index fill20250517_fresh_index_hm_prod_consortium_entities must be read-only to resize index. use \"index.blocks.write=true\""}],"type":"illegal_state_exception","reason":"index fill20250517_fresh_index_hm_prod_consortium_entities must be read-only to resize index. use \"index.blocks.write=true\""},"status":500}
Traceback (most recent call last):
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 745, in <module>
    swap_index_names_per_strategy(es_mgr=esmanager
  File "/usr/src/app/scripts/fresh_indices/fresh_indices.py", line 383, in swap_index_names_per_strategy
    es_mgr.clone_index(source_index_name=destination_index
  File "/usr/src/app/scripts/fresh_indices/es_manager.py", line 267, in clone_index
    raise Exception(f"Failed to clone source index: {source_index_name} "
Exception: Failed to clone source index: fill20250517_fresh_index_hm_prod_consortium_entities  to target index: hm_prod_consortium_entities with status_code-500, reason-index fill20250517_fresh_index_hm_prod_consortium_entities must be read-only to resize index. use "index.blocks.write=true". See logs.
```

<img width="905" alt="Image" src="https://github.com/user-attachments/assets/0780a501-5872-46de-99f6-de4c0c4bc561" />

**Comment by yuanzhou** [comment]
5/18/2025, ran another round of full reindex overnight, and all went as expected this time. @kburke for the record

**Comment by yuanzhou** [comment]
11/01/2025 Full reindex completed but with some failed ids, and the ids list contains duplicates. We should ensure the failed list only contains unique ids.
