### ISSUE TITLE
Investigate 403 assaytype error from CloudWatch alarm

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#905]
```
[2024-10-30 17:27:53] ERROR in hubmap_translator:898: Exceptions during executing translate()
Traceback (most recent call last):
  File "/usr/src/app/src/./hubmap_translator.py", line 772, in translate
    result = f.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/src/./hubmap_translator.py", line 625, in _exec_reindex_entity_to_index_group_by_id
    self._transform_and_write_entity_to_index_group(entity=entity
  File "/usr/src/app/src/./hubmap_translator.py", line 672, in _transform_and_write_entity_to_index_group
    private_transformed = transformer.transform(json.loads(private_doc),
  File "/usr/src/app/src/./hubmap_translation/addl_index_transformations/portal/__init__.py", line 71, in transform
    add_assay_details(doc_copy, transformation_resources)
  File "/usr/src/app/src/./hubmap_translation/addl_index_transformations/portal/add_assay_details.py", line 135, in add_assay_details
    assay_details = _get_assay_details(doc, transformation_resources)
  File "/usr/src/app/src/./hubmap_translation/addl_index_transformations/portal/add_assay_details.py", line 50, in _get_assay_details
    raise e
  File "/usr/src/app/src/./hubmap_translation/addl_index_transformations/portal/add_assay_details.py", line 42, in _get_assay_details
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://ingest.api.hubmapconsortium.org/assaytype/4274c023697e1fd68433f4b8c7a150c0
```

```
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://ingest.api.hubmapconsortium.org/assaytype/28adfdab2632a2da190b1ffda55edbce
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://ingest.api.hubmapconsortium.org/assaytype/4274c023697e1fd68433f4b8c7a150c0
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://ingest.api.hubmapconsortium.org/assaytype/b279489f1381b60810d6494a68b829ac
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://ingest.api.hubmapconsortium.org/assaytype/be25590e514b671f5adc79e3abb210a8
```

**Comment by yuanzhou** [comment]
John and I tested with our personal tokens, all worked fine.

**Comment by yuanzhou** [comment]
From CloudWatch logging search, could not find any `/reindex/<id>` made from outside that match the target. Only found the one I triggered in Postman AFTER the alarm.

**Comment by yuanzhou** [comment]
Can't reproduce and couldn't figure out based on logging. There's a chance that the token expired.
